name: UAT Deploy NIA University API

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout
      - name: Checkout Code
        uses: actions/checkout@v4

      # 2. Setup .NET
      - name: Setup .NET 8
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: 8.0.x

      # 3. Restore
      - name: Restore Packages
        run: dotnet restore

      # 3.5 Replace CORS Origin for Production
      - name: Replace CORS Origin
        run: |
          sed -i 's|https://localhost:7266|${{ secrets.UAT_CORS_ORIGIN }}|g' Program.cs

      # 4. Build
      - name: Build Application
        run: dotnet build --configuration Release --no-restore

      # 5. Publish
      - name: Publish Application
        run: dotnet publish -c Release -o ./publish

      # 6. Upload to TEMP folder (important)
      - name: Upload to Server (TEMP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          source: "publish/*"
          target: "/var/www/UAT_NIA_university_api_temp"
          strip_components: 1

      # 7. Deploy on server
      - name: Deploy & Restart API
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: root
          key: ${{ secrets.SERVER_SSH_KEY }}
          script: |
            echo "🧹 Cleaning old deployment"
            mkdir -p /var/www/uat_NIA_University/NIA_universityAPI/Deployment/publish
            rm -rf /var/www/uat_NIA_University/NIA_universityAPI/Deployment/publish/*

            echo "🚀 Copy new build"
            cp -r /var/www/UAT_NIA_university_api_temp/. /var/www/uat_NIA_University/NIA_universityAPI/Deployment/publish/

            echo "🧹 Remove temp"
            rm -rf /var/www/UAT_NIA_university_api_temp

            echo "🔐 Fix permissions"
            chown -R www-data:www-data /var/www/uat_NIA_University

            echo "🔁 Restart service"
            systemctl daemon-reload
            systemctl restart uat_nia_university_api.service

            echo "✅ Status"
            systemctl status uat_nia_university_api.service --no-pager
